# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lenet5/lenet5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5 || ORIG_REF_NAME==lenet5} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_processing_system7_0_0/lenet5_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_processing_system7_0_0 || ORIG_REF_NAME==lenet5_processing_system7_0_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_lenet5_top_0_0/lenet5_lenet5_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_lenet5_top_0_0 || ORIG_REF_NAME==lenet5_lenet5_top_0_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_blk_mem_gen_0_0/lenet5_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_blk_mem_gen_0_0 || ORIG_REF_NAME==lenet5_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_blk_mem_gen_0_1/lenet5_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_blk_mem_gen_0_1 || ORIG_REF_NAME==lenet5_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_blk_mem_gen_0_2/lenet5_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_blk_mem_gen_0_2 || ORIG_REF_NAME==lenet5_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_blk_mem_gen_0_3/lenet5_blk_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_blk_mem_gen_0_3 || ORIG_REF_NAME==lenet5_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_axi_bram_ctrl_0_0/lenet5_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_axi_bram_ctrl_0_0 || ORIG_REF_NAME==lenet5_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_axi_bram_ctrl_1_0/lenet5_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_axi_bram_ctrl_1_0 || ORIG_REF_NAME==lenet5_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_axi_bram_ctrl_1_1/lenet5_axi_bram_ctrl_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_axi_bram_ctrl_1_1 || ORIG_REF_NAME==lenet5_axi_bram_ctrl_1_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_axi_gpio_0_0/lenet5_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_axi_gpio_0_0 || ORIG_REF_NAME==lenet5_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlslice_0_0/lenet5_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlslice_0_0 || ORIG_REF_NAME==lenet5_xlslice_0_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlslice_0_1/lenet5_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlslice_0_1 || ORIG_REF_NAME==lenet5_xlslice_0_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlconcat_0_0/lenet5_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlconcat_0_0 || ORIG_REF_NAME==lenet5_xlconcat_0_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlslice_3_0/lenet5_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlslice_3_0 || ORIG_REF_NAME==lenet5_xlslice_3_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlslice_3_1/lenet5_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlslice_3_1 || ORIG_REF_NAME==lenet5_xlslice_3_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_rst_ps7_0_100M_1/lenet5_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_rst_ps7_0_100M_1 || ORIG_REF_NAME==lenet5_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xbar_1/lenet5_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xbar_1 || ORIG_REF_NAME==lenet5_xbar_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_axi_interconnect_0_1/lenet5_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_axi_interconnect_0_1 || ORIG_REF_NAME==lenet5_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_auto_pc_2/lenet5_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_auto_pc_2 || ORIG_REF_NAME==lenet5_auto_pc_2} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_auto_ds_1/lenet5_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_auto_ds_1 || ORIG_REF_NAME==lenet5_auto_ds_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_processing_system7_0_0_1/lenet5_processing_system7_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_processing_system7_0_0 || ORIG_REF_NAME==lenet5_processing_system7_0_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_bram_ctrl_a_0/lenet5_bram_ctrl_a_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_bram_ctrl_a_0 || ORIG_REF_NAME==lenet5_bram_ctrl_a_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_bram_ctrl_b_0/lenet5_bram_ctrl_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_bram_ctrl_b_0 || ORIG_REF_NAME==lenet5_bram_ctrl_b_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_bram_ctrl_pesos_0/lenet5_bram_ctrl_pesos_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_bram_ctrl_pesos_0 || ORIG_REF_NAME==lenet5_bram_ctrl_pesos_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_rst_ps7_0_100M_0/lenet5_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_rst_ps7_0_100M_0 || ORIG_REF_NAME==lenet5_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xbar_0/lenet5_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xbar_0 || ORIG_REF_NAME==lenet5_xbar_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlconstant_0_1/lenet5_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlconstant_0_1 || ORIG_REF_NAME==lenet5_xlconstant_0_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlslice_3_2/lenet5_xlslice_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlslice_3_2 || ORIG_REF_NAME==lenet5_xlslice_3_2} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlconstant_0_2/lenet5_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlconstant_0_2 || ORIG_REF_NAME==lenet5_xlconstant_0_2} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_xlslice_2_0/lenet5_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_xlslice_2_0 || ORIG_REF_NAME==lenet5_xlslice_2_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_auto_pc_1/lenet5_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_auto_pc_1 || ORIG_REF_NAME==lenet5_auto_pc_1} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_auto_us_0/lenet5_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_auto_us_0 || ORIG_REF_NAME==lenet5_auto_us_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_auto_ds_0/lenet5_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_auto_ds_0 || ORIG_REF_NAME==lenet5_auto_ds_0} -quiet] -quiet

# IP: bd/lenet5/ip/lenet5_auto_pc_0/lenet5_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet5_auto_pc_0 || ORIG_REF_NAME==lenet5_auto_pc_0} -quiet] -quiet

# XDC: bd/lenet5/ip/lenet5_blk_mem_gen_0_0/lenet5_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/lenet5/ip/lenet5_blk_mem_gen_0_1/lenet5_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/lenet5/ip/lenet5_blk_mem_gen_0_2/lenet5_blk_mem_gen_0_2_ooc.xdc

# XDC: bd/lenet5/ip/lenet5_blk_mem_gen_0_3/lenet5_blk_mem_gen_0_3_ooc.xdc

# XDC: bd/lenet5/ip/lenet5_axi_gpio_0_0/lenet5_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lenet5_axi_gpio_0_0 || ORIG_REF_NAME==lenet5_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lenet5/ip/lenet5_axi_gpio_0_0/lenet5_axi_gpio_0_0_ooc.xdc

# XDC: bd/lenet5/ip/lenet5_axi_gpio_0_0/lenet5_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lenet5_axi_gpio_0_0 || ORIG_REF_NAME==lenet5_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lenet5/ip/lenet5_processing_system7_0_0_1/lenet5_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lenet5_processing_system7_0_0 || ORIG_REF_NAME==lenet5_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/lenet5/ip/lenet5_rst_ps7_0_100M_0/lenet5_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lenet5_rst_ps7_0_100M_0 || ORIG_REF_NAME==lenet5_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lenet5/ip/lenet5_rst_ps7_0_100M_0/lenet5_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lenet5_rst_ps7_0_100M_0 || ORIG_REF_NAME==lenet5_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lenet5/ip/lenet5_auto_pc_1/lenet5_auto_pc_1_ooc.xdc

# XDC: bd/lenet5/ip/lenet5_auto_us_0/lenet5_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lenet5_auto_us_0 || ORIG_REF_NAME==lenet5_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/lenet5/ip/lenet5_auto_us_0/lenet5_auto_us_0_ooc.xdc

# XDC: bd/lenet5/ip/lenet5_auto_ds_0/lenet5_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lenet5_auto_ds_0 || ORIG_REF_NAME==lenet5_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/lenet5/ip/lenet5_auto_ds_0/lenet5_auto_ds_0_ooc.xdc

# XDC: bd/lenet5/ip/lenet5_auto_pc_0/lenet5_auto_pc_0_ooc.xdc

# XDC: bd/lenet5/lenet5_ooc.xdc
